Fix/feedbacks
mapswipe/python-mapswipe-workers pull request #588
Opened 2022-11-21 11:51 UTC by thenav56

- Use total_swipes instead of task_count.
- Remove total_user_groups from User Node.
- Set MAX_PAGINATION_LIMIT to 500

2022-11-22 09:15 UTC, k9845 approved these changes

2022-11-23 08:59 UTC, frozenhelium commented on manager-dashboard/app/views/Projects/ProjectDetails/index.tsx
> +                        <div className={styles.projectVisibility}>
Add following styling for this
```css
.project-visibility {
    display: flex;
    align-items: center;
    gap: var(--spacing-small);
}
```

2022-11-23 09:51 UTC, frozenhelium approved these changes

2022-11-23 11:45 UTC, tnagorra commented on community-dashboard/app/views/UserDashboard/index.tsx
> +    const totalUserGroup = userStats?.user?.userInUserGroups?.count ?? 0;
What is the difference between totalUserGroup and userGroupsLength?

2022-11-23 11:51 UTC, tnagorra requested changes

2022-11-23 11:51 UTC, tnagorra commented on example.env
> +MANAGER_DASHBOARD_COMMUNITY_DASHBOARD_URL=https://community-dashboard.mapswipe.org
```suggestion
MANAGER_DASHBOARD_COMMUNITY_DASHBOARD_URL=
```

Should we have values on example.env?

2022-11-23 11:53 UTC, thenav56 commented on example.env
> +MANAGER_DASHBOARD_COMMUNITY_DASHBOARD_URL=https://community-dashboard.mapswipe.org
Yes.

2022-11-23 13:08 UTC, tnagorra commented on community-dashboard/app/views/UserDashboard/index.tsx
> +    const totalUserGroup = userStats?.user?.userInUserGroups?.count ?? 0;
Fixed!

2022-11-23 13:12 UTC, tnagorra approved these changes

2022-11-24 19:05 UTC, merged